version: 0.2
env:
  shell: bash
phases: 
  pre_build: 
    commands: 
    - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain agama --domain-owner 270167558056 --query authorizationToken --output text --region us-east-1`
    - . ~/.profile    
  build: 
    commands: 
    - echo Build started on `date`
    - cp ./settings.xml /root/.m2/settings.xml 
    - mvn test
    - mvn validate -DbumpMajor
    - mvn --batch-mode release:prepare
    - mvn clean deploy